version: 0.2

phases:
  install:
    commands:
      # install node 14 (npm comes with it): obtrained here: https://github.com/nodesource/distributions/blob/master/README.md
      - echo Installing Node.js 12...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      # tests
      # build
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
